--Paso 1
-- ALTER TABLE [dbo].[ADMON_USUARIOS] ADD CURP VARCHAR(18);

--Paso 2
-- UPDATE [dbo].[ADMON_USUARIOS]
--   SET CURP = 'XX'

--Paso 3
ALTER TABLE [dbo].[ADMON_USUARIOS] ALTER COLUMN CURP VARCHAR(18) NOT NULL;

