USE [CMRISE]
GO
--(Paso 1)
--ALTER TABLE dbo.MRQS_PREGUNTAS_FTA ADD SINGLE_ANSWER_MODE BIT;
--ALTER TABLE dbo.MRQS_PREGUNTAS_FTA ADD SUFFLE_ANSWER_ORDER BIT;

--(Paso 2)
--UPDATE  dbo.MRQS_PREGUNTAS_FTA
--SET SINGLE_ANSWER_MODE = 0
--   ,SUFFLE_ANSWER_ORDER = 0

--(Paso 3)
ALTER TABLE dbo.MRQS_PREGUNTAS_FTA ALTER COLUMN SINGLE_ANSWER_MODE BIT NOT NULL; 
ALTER TABLE dbo.MRQS_PREGUNTAS_FTA ALTER COLUMN SUFFLE_ANSWER_ORDER BIT NOT NULL;

