Reglas de Campos 
NUMERO BIGINT
Longitud de campos ligados a dbo.TABLAS_UTILITARIAS_VALORES VARCHAR(30) 
Campos tipo TextArea seran VARCHAR(500)
TITULO_PREGUNTA     VARCHAR(200)
TEXTO_PREGUNTA      VARCHAR(500)
TEXTO_SUGERENCIAS   VARCHAR(500)
RESPUESTA_CORRECTA  VARCHAR(500)