USE [CMRISE]
GO

CREATE VIEW [dbo].[ADMON_CANDIDATOS_V1]
AS
SELECT        NUMERO_USUARIO
     , NUMERO_ROL, NOMBRE_COMPLETO_USUARIO, CURP, DESCRIPCION_ROL, CORREO_ELECTRONICO
FROM            dbo.ADMON_USUARIOS_ROLES_V1
WHERE        (NUMERO_ROL = '1')
GO