USE [CMRISE]
GO

CREATE OR ALTER VIEW CAND_EXAMENES_V2 AS 
SELECT CEV1.[NUMERO]
      ,CEV1.[NUMERO_USUARIO]
      ,CEV1.[NUMERO_EXAMEN]
      ,CEV1.[TIPO]
      ,CEV1.[ESTATUS]
      ,CEV1.[CREADO_POR]
      ,CEV1.[FECHA_CREACION]
      ,CEV1.[ACTUALIZADO_POR]
      ,CEV1.[FECHA_ACTUALIZACION]
      ,CEV1.[MATRICULA]
      ,CEV1.[NOMBRE_USUARIO]
      ,CEV1.[APELLIDO_PATERNO]
      ,CEV1.[APELLIDO_MATERNO]
      ,CEV1.[NOMBRE_COMPLETO_USUARIO]
      ,CEV1.[NOMBRE_ROL]
      ,CEV1.[DESCRIPCION_ROL]
	  ,ME.TITULO
	  ,ME.TIEMPO_LIMITE
  FROM [dbo].[CAND_EXAMENES_V1] CEV1
      ,[dbo].[MRQS_EXAMENES] ME
  WHERE CEV1.TIPO = 'MRQS'
    AND CEV1.NUMERO_EXAMEN = ME.NUMERO
GO


