USE [CMRISE]
GO

/****** Object:  View [dbo].[CC_EXAM_ASIGNACIONES_V1]    Script Date: 18/02/2020 11:16:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE   VIEW [dbo].[CC_EXAM_ASIGNACIONES_V1] AS
SELECT ROW_NUMBER() OVER (ORDER BY CPH.TITULO ASC) ID
      ,CEA.[NUMERO]
      ,CEA.[NUMERO_CC_EXAMEN]
      ,CEA.[NUMERO_CORE_CASE]
      ,CEA.[FECHA_EFECTIVA_DESDE]
      ,CEA.[FECHA_EFECTIVA_HASTA]
      ,CEA.[CREADO_POR]
      ,CEA.[FECHA_CREACION]
      ,CEA.[ACTUALIZADO_POR]
      ,CEA.[FECHA_ACTUALIZACION]
	  ,CPH.NUMERO NUMERO_PREGUNTA
	  ,CPH.TITULO TITULO_PREGUNTA
	  ,CPH.ESTATUS
	  ,TUV1.SIGNIFICADO ESTATUS_DESC
	  ,CPH.TEMA_PREGUNTA
	  ,TUV2.SIGNIFICADO TEMA_PREGUNTA_DESC
      ,ISNULL(CPH.MAX_PUNTUACION,0.00) MAX_PUNTUACION
	  ,CPH.ETIQUETAS
  FROM [dbo].[CC_EXAM_ASIGNACIONES] CEA
      ,[dbo].[CC_PREGUNTAS_HDR] CPH
	  ,[dbo].[TABLAS_UTILITARIAS_VALORES] TUV1
	  ,[dbo].[TABLAS_UTILITARIAS_VALORES] TUV2
   WHERE CEA.NUMERO_CORE_CASE = CPH.NUMERO_CC_HDR   
    AND TUV1.TIPO_TABLA='ESTATUS_MRQ'
    AND TUV1.CODIGO_TABLA = CPH.ESTATUS
    AND TUV2.TIPO_TABLA='TEMA_DE_PREGUNTA'
    AND TUV2.CODIGO_TABLA = CPH.TEMA_PREGUNTA
GO


