USE [CMRISE]
GO

CREATE OR ALTER VIEW CC_EXAMENES_V1 AS
SELECT CE.[NUMERO]
      ,CE.[TITULO]
      ,CE.[NOMBRE]
      ,CE.[DESCRIPCION]
      ,CE.[COMENTARIOS]
      ,CE.[TIEMPO_LIMITE]
      ,CE.[SALTAR_PREGUNTAS]
      ,CE.[SALTAR_CASOS]
      ,CE.[MOSTRAR_RESPUESTAS]
      ,CE.[TIENE_PASSMARK]
      ,CE.[ALEATORIO_GRUPO]
      ,CE.[ALEATORIO_PREGUNTAS]
      ,CE.[SELECCION_CASOS_ALEATORIOS]
      ,CE.[MENSAJE_FINALIZACION]
      ,CE.[CONFIRMACION_ASISTENCIA]
      ,CE.[DIPLOMA]
      ,CE.[TIPO_PREGUNTA]
	  ,TUV5.SIGNIFICADO TIPO_PREGUNTA_DESC
      ,CE.[TIPO_EXAMEN]
	  ,TUV1.SIGNIFICADO TIPO_EXAMEN_DESC
      ,CE.[VISIBILIDAD]
	  ,TUV2.SIGNIFICADO VISIBILIDAD_DESC 
      ,CE.[ESTATUS]
	  ,TUV3.SIGNIFICADO ESTATUS_DESC
      ,CE.[TEMA]
	  ,TUV4.SIGNIFICADO TEMA_DESC
      ,CE.[SOCIEDAD]
      ,CE.[FECHA_EFECTIVA_DESDE]
      ,CE.[FECHA_EFECTIVA_HASTA]
      ,CE.[CREADO_POR]
      ,CE.[FECHA_CREACION]
      ,CE.[ACTUALIZADO_POR]
      ,CE.[FECHA_ACTUALIZACION]
  FROM [dbo].[CC_EXAMENES] CE
      ,[dbo].[TABLAS_UTILITARIAS_VALORES] TUV1
	  ,[dbo].[TABLAS_UTILITARIAS_VALORES] TUV2
	  ,[dbo].[TABLAS_UTILITARIAS_VALORES] TUV3
	  ,[dbo].[TABLAS_UTILITARIAS_VALORES] TUV4
	  ,[dbo].[TABLAS_UTILITARIAS_VALORES] TUV5
 WHERE TUV1.TIPO_TABLA='TIPO_EXAMEN'
   AND TUV2.TIPO_TABLA='VISIBILIDAD_EXAMEN'
   AND TUV3.TIPO_TABLA='ESTATUS_EXAMEN'
   AND TUV4.TIPO_TABLA='TEMA_DE_EXAMEN'
   AND TUV5.TIPO_TABLA='TIPO_PREGUNTA'
   AND TUV1.CODIGO_TABLA = CE.[TIPO_EXAMEN]
   AND TUV2.CODIGO_TABLA = CE.[VISIBILIDAD]
   AND TUV3.CODIGO_TABLA = CE.[ESTATUS]
   AND TUV4.CODIGO_TABLA = CE.[TEMA]
   AND TUV5.CODIGO_TABLA = CE.[TIPO_PREGUNTA]
GO


