USE [CMRISE]
GO

CREATE OR ALTER VIEW CC_PREGUNTAS_FTA_V1 AS
SELECT [NUMERO]
      ,[NUMERO_HDR]
      ,[TITULO_PREGUNTA]
      ,[TEXTO_PREGUNTA]
      ,[TEXTO_SUGERENCIAS]
      ,[RESPUESTA_CORRECTA]
      ,[FECHA_EFECTIVA_DESDE]
      ,[FECHA_EFECTIVA_HASTA]
      ,[CREADO_POR]
      ,[FECHA_CREACION]
      ,[ACTUALIZADO_POR]
      ,[FECHA_ACTUALIZACION]
  FROM [dbo].[CC_PREGUNTAS_FTA]
GO


