USE [CMRISE]
GO

CREATE OR ALTER VIEW CC_PREGUNTAS_HDR_V1 AS
SELECT CPH.[NUMERO]
      ,CPH.[NUMERO_CC_HDR]
      ,CPH.[NOMBRE]
      ,CPH.[TITULO]
      ,CPH.[TIPO_PREGUNTA]
	  ,TUV1.[SIGNIFICADO] TIPO_PREGUNTA_DESC
      ,CPH.[TEMA_PREGUNTA]
	  ,TUV2.[SIGNIFICADO] TEMA_PREGUNTA_DESC
      ,CPH.[ETIQUETAS]
      ,CPH.[COMENTARIOS]
      ,CPH.[ESTATUS]
	  ,TUV3.[SIGNIFICADO] ESTATUS_DESC
      ,CPH.[SOCIEDAD]
      ,CPH.[FECHA_EFECTIVA_DESDE]
      ,CPH.[FECHA_EFECTIVA_HASTA]
      ,CPH.[CREADO_POR]
      ,CPH.[FECHA_CREACION]
      ,CPH.[ACTUALIZADO_POR]
      ,CPH.[FECHA_ACTUALIZACION]
  FROM [dbo].[CC_PREGUNTAS_HDR] CPH
      ,[dbo].[TABLAS_UTILITARIAS_VALORES] TUV1
	  ,[dbo].[TABLAS_UTILITARIAS_VALORES] TUV2
	  ,[dbo].[TABLAS_UTILITARIAS_VALORES] TUV3
 WHERE TUV1.TIPO_TABLA = 'TIPO_PREGUNTA'
   AND TUV2.TIPO_TABLA = 'TEMA_DE_PREGUNTA'
   AND TUV3.TIPO_TABLA = 'ESTATUS_MRQ'
   AND TUV1.CODIGO_TABLA = CPH.TIPO_PREGUNTA
   AND TUV2.CODIGO_TABLA = CPH.TEMA_PREGUNTA
   AND TUV3.CODIGO_TABLA = CPH.ESTATUS
GO


