USE [CMRISE]
GO

/****** Object:  View [dbo].[MRQS_GRUPO_LINES_V1]    Script Date: 01/04/2020 13:14:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE OR ALTER  VIEW [dbo].[MRQS_GRUPO_LINES_V2] AS
SELECT MGH.TITULO TITULO_GRUPO
      ,MGL.[NUMERO]
      ,MGL.[NUMERO_HDR]
      ,MGL.[NUMERO_PREGUNTA]
      ,MGL.[CREADO_POR]
      ,MGL.[FECHA_CREACION]
      ,MGL.[ACTUALIZADO_POR]
      ,MGL.[FECHA_ACTUALIZACION]
	  ,MPHV2.TITULO
	  ,MPHV2.TIPO_PREGUNTA
	  ,MPHV2.TIPO_PREGUNTA_DESC
	  ,MPHV2.ESTATUS
	  ,MPHV2.ESTATUS_DESC
	  ,MPHV2.TEMA_PREGUNTA
      ,MPHV2.TEMA_PREGUNTA_DESC
	  ,MPHV2.ETIQUETAS
	  ,MPHV2.TEXTO_PREGUNTA
	  ,MPHV2.TEXTO_SUGERENCIAS
	  ,MPHV2.SINGLE_ANSWER_MODE
	  ,MPHV2.SUFFLE_ANSWER_ORDER
  FROM [dbo].[MRQS_GRUPO_HDR] MGH
      ,[dbo].[MRQS_GRUPO_LINES] MGL
      ,[dbo].[MRQS_PREGUNTAS_HDR_V2] MPHV2
 WHERE MPHV2.NUMERO = MGL.NUMERO_PREGUNTA
   AND MGH.NUMERO = MGL.NUMERO_HDR
GO


