USE [CMRISE]
GO

CREATE OR ALTER VIEW MRQS_GRUPO_LINES_V1 AS
SELECT MGL.[NUMERO]
      ,MGL.[NUMERO_HDR]
      ,MGL.[NUMERO_PREGUNTA]
      ,MGL.[CREADO_POR]
      ,MGL.[FECHA_CREACION]
      ,MGL.[ACTUALIZADO_POR]
      ,MGL.[FECHA_ACTUALIZACION]
	  ,MPHV1.TITULO
	  ,MPHV1.TIPO_PREGUNTA
	  ,MPHV1.TIPO_PREGUNTA_DESC
	  ,MPHV1.ESTATUS
	  ,MPHV1.ESTATUS_DESC
	  ,MPHV1.TEMA_PREGUNTA
      ,MPHV1.TEMA_PREGUNTA_DESC
	  ,MPHV1.ETIQUETAS
  FROM [dbo].[MRQS_GRUPO_LINES] MGL
      ,[dbo].[MRQS_PREGUNTAS_HDR_V1] MPHV1
 WHERE MPHV1.NUMERO = MGL.NUMERO_PREGUNTA
GO


