USE [CMRISE]
GO


CREATE OR ALTER   VIEW [dbo].[MRQS_PREGUNTAS_HDR_V1] AS
SELECT MPH.[NUMERO]
      ,MPH.[NOMBRE]
      ,MPH.[TITULO]
      ,MPH.[TIPO_PREGUNTA]
	  ,TUV1.SIGNIFICADO  TIPO_PREGUNTA_DESC
	  ,MPH.[TEMA_PREGUNTA]
	  ,TUV2.SIGNIFICADO  TEMA_PREGUNTA_DESC
      ,MPH.[ETIQUETAS]
      ,MPH.[COMENTARIOS]
      ,MPH.[ESTATUS]
	  ,TUV3.[SIGNIFICADO] ESTATUS_DESC
      ,MPH.[SOCIEDAD]
      ,MPH.[FECHA_EFECTIVA_DESDE]
      ,MPH.[FECHA_EFECTIVA_HASTA]
      ,MPH.[CREADO_POR]
      ,MPH.[FECHA_CREACION]
      ,MPH.[ACTUALIZADO_POR]
      ,MPH.[FECHA_ACTUALIZACION]
  FROM [dbo].[MRQS_PREGUNTAS_HDR] MPH
      ,[dbo].TABLAS_UTILITARIAS_VALORES TUV1
	  ,[dbo].TABLAS_UTILITARIAS_VALORES TUV2
	  ,[dbo].TABLAS_UTILITARIAS_VALORES TUV3
  WHERE TUV1.TIPO_TABLA = 'TIPO_PREGUNTA'
    AND TUV1.CODIGO_TABLA = MPH.TIPO_PREGUNTA
	AND TUV2.TIPO_TABLA = 'TEMA_DE_PREGUNTA'
    AND TUV2.CODIGO_TABLA = MPH.TEMA_PREGUNTA
	AND TUV3.TIPO_TABLA = 'ESTATUS_MRQ'
    AND TUV3.CODIGO_TABLA = MPH.ESTATUS


GO


