USE [CMRISE]
GO

/****** Object:  Table [dbo].[ADMON_ROLES]    Script Date: 20/01/2020 15:25:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ADMON_USUARIOS_ROLES](
	[NUMERO] [bigint] NOT NULL DEFAULT (NEXT VALUE FOR [DBO].[ADMON_USUARIOS_ROLES_S]) ,
	[NUMERO_USUARIO] bigint NOT NULL,
	[NUMERO_ROL] bigint NOT NULL,
	[FECHA_EFECTIVA_DESDE] [date] NOT NULL,
	[FECHA_EFECTIVA_HASTA] [date] NOT NULL,
	[CREADO_POR] [bigint] NOT NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[ACTUALIZADO_POR] [bigint] NOT NULL,
	[FECHA_ACTUALIZACION] [datetime] NOT NULL,
	CONSTRAINT ADMON_USUARIOS_ROLES_PK1 PRIMARY KEY(NUMERO),
	CONSTRAINT ADMON_USUARIOS_ROLES_FK2 FOREIGN KEY(NUMERO_USUARIO) REFERENCES [dbo].[ADMON_USUARIOS](NUMERO),
	CONSTRAINT ADMON_USUARIOS_ROLES_FK3 FOREIGN KEY(NUMERO_ROL) REFERENCES [dbo].[ADMON_ROLES](NUMERO),
    ) 


