USE [CMRISE]
GO

ALTER TABLE [dbo].[ADMON_CC_CANDIDATOS] DROP CONSTRAINT [ADMON_CANDIDATOS_FK2]
GO

ALTER TABLE [dbo].[ADMON_CC_CANDIDATOS] DROP CONSTRAINT [ADMON_CANDIDATOS_FK1]
GO

ALTER TABLE [dbo].[ADMON_CC_CANDIDATOS] DROP CONSTRAINT [DF__ADMON_CC___NUMER__671F4F74]
GO

/****** Object:  Table [dbo].[ADMON_CC_CANDIDATOS]    Script Date: 27/02/2020 17:50:00 ******/
DROP TABLE [dbo].[ADMON_CC_CANDIDATOS]
GO

/****** Object:  Table [dbo].[ADMON_CC_CANDIDATOS]    Script Date: 27/02/2020 17:50:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ADMON_CC_CANDIDATOS](
	[NUMERO] [bigint] NOT NULL,
	[NUMERO_USUARIO] [bigint] NOT NULL,
	[NUMERO_CC_EXAMEN] [bigint] NOT NULL,
	[INFORMACION_EXTRA] [varchar](500) NULL,
	[FECHA_EFECTIVA_DESDE] [date] NOT NULL,
	[FECHA_EFECTIVA_HASTA] [date] NOT NULL,
	[CREADO_POR] [bigint] NOT NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[ACTUALIZADO_POR] [bigint] NOT NULL,
	[FECHA_ACTUALIZACION] [datetime] NOT NULL,
 CONSTRAINT [ADMON_CANDIDATOS_PK1] PRIMARY KEY CLUSTERED 
(
	[NUMERO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ADMON_CC_CANDIDATOS] ADD  DEFAULT (NEXT VALUE FOR [ADMON_CC_CANDIDATOS_S]) FOR [NUMERO]
GO

ALTER TABLE [dbo].[ADMON_CC_CANDIDATOS]  WITH CHECK ADD  CONSTRAINT [ADMON_CANDIDATOS_FK1] FOREIGN KEY([NUMERO_USUARIO])
REFERENCES [dbo].[ADMON_USUARIOS] ([NUMERO])
GO

ALTER TABLE [dbo].[ADMON_CC_CANDIDATOS] CHECK CONSTRAINT [ADMON_CANDIDATOS_FK1]
GO

ALTER TABLE [dbo].[ADMON_CC_CANDIDATOS]  WITH CHECK ADD  CONSTRAINT [ADMON_CANDIDATOS_FK2] FOREIGN KEY([NUMERO_CC_EXAMEN])
REFERENCES [dbo].[CC_EXAMENES] ([NUMERO])
GO

ALTER TABLE [dbo].[ADMON_CC_CANDIDATOS] CHECK CONSTRAINT [ADMON_CANDIDATOS_FK2]
GO


