USE [CMRISE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CAND_EXAMENES](
	[NUMERO] [bigint] NOT NULL DEFAULT(NEXT VALUE FOR [DBO].[CAND_EXAMENES_S]),
	[NUMERO_USUARIO] [bigint] NOT NULL, 
	[NUMERO_EXAMEN] [bigint] NOT NULL,
	[TIPO] VARCHAR(30) NOT NULL,
	[ESTATUS] VARCHAR(30) NOT NULL,
	[CREADO_POR] [bigint] NOT NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[ACTUALIZADO_POR] [bigint] NOT NULL,
	[FECHA_ACTUALIZACION] [datetime] NOT NULL,
	CONSTRAINT CAND_EXAMENES_PK1 PRIMARY KEY(NUMERO),
	CONSTRAINT CAND_EXAMENES_FK1 FOREIGN KEY(NUMERO_USUARIO) REFERENCES [dbo].[ADMON_USUARIOS](NUMERO),
	CONSTRAINT CAND_EXAMENES_U1 UNIQUE (NUMERO_USUARIO,NUMERO_EXAMEN,TIPO)
)


