USE [CMRISE]
GO

ALTER TABLE [dbo].[CAND_CC_EXAMENES] DROP CONSTRAINT [CAND_CC_EXAMENES_FK2]
GO

ALTER TABLE [dbo].[CAND_CC_EXAMENES] DROP CONSTRAINT [CAND_CC_EXAMENES_FK1]
GO

ALTER TABLE [dbo].[CAND_CC_EXAMENES] DROP CONSTRAINT [DF__CAND_CC_E__NUMER__7C1A6C5A]
GO

/****** Object:  Table [dbo].[CAND_CC_EXAMENES]    Script Date: 27/02/2020 17:52:52 ******/
DROP TABLE [dbo].[CAND_CC_EXAMENES]
GO

/****** Object:  Table [dbo].[CAND_CC_EXAMENES]    Script Date: 27/02/2020 17:52:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CAND_CC_EXAMENES](
	[NUMERO] [bigint] NOT NULL,
	[NUMERO_CC_EXAMEN] [bigint] NOT NULL,
	[NUMERO_USUARIO] [bigint] NOT NULL,
	[ESTATUS] [varchar](30) NOT NULL,
	[FECHA_EFECTIVA_DESDE] [datetime] NOT NULL,
	[FECHA_EFECTIVA_HASTA] [datetime] NOT NULL,
	[CREADO_POR] [bigint] NOT NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[ACTUALIZADO_POR] [bigint] NOT NULL,
	[FECHA_ACTUALIZACION] [datetime] NOT NULL,
 CONSTRAINT [CAND_CC_EXAMENES_PK] PRIMARY KEY CLUSTERED 
(
	[NUMERO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CAND_CC_EXAMENES] ADD  DEFAULT (NEXT VALUE FOR [CAND_CC_EXAMENES_S]) FOR [NUMERO]
GO

ALTER TABLE [dbo].[CAND_CC_EXAMENES]  WITH CHECK ADD  CONSTRAINT [CAND_CC_EXAMENES_FK1] FOREIGN KEY([NUMERO_CC_EXAMEN])
REFERENCES [dbo].[CC_EXAMENES] ([NUMERO])
GO

ALTER TABLE [dbo].[CAND_CC_EXAMENES] CHECK CONSTRAINT [CAND_CC_EXAMENES_FK1]
GO

ALTER TABLE [dbo].[CAND_CC_EXAMENES]  WITH CHECK ADD  CONSTRAINT [CAND_CC_EXAMENES_FK2] FOREIGN KEY([NUMERO_USUARIO])
REFERENCES [dbo].[ADMON_USUARIOS] ([NUMERO])
GO

ALTER TABLE [dbo].[CAND_CC_EXAMENES] CHECK CONSTRAINT [CAND_CC_EXAMENES_FK2]
GO


