USE [CMRISE]
GO

ALTER TABLE [dbo].[CAND_CC_PREGUNTAS_FTA] DROP CONSTRAINT [CAND_CC_PREGUNTAS_FTA_FK2]
GO

ALTER TABLE [dbo].[CAND_CC_PREGUNTAS_FTA] DROP CONSTRAINT [CAND_CC_PREGUNTAS_FTA_FK1]
GO

ALTER TABLE [dbo].[CAND_CC_PREGUNTAS_FTA] DROP CONSTRAINT [DF__CAND_CC_P__NUMER__36470DEF]
GO

/****** Object:  Table [dbo].[CAND_CC_PREGUNTAS_FTA]    Script Date: 27/02/2020 17:53:24 ******/
DROP TABLE [dbo].[CAND_CC_PREGUNTAS_FTA]
GO

/****** Object:  Table [dbo].[CAND_CC_PREGUNTAS_FTA]    Script Date: 27/02/2020 17:53:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CAND_CC_PREGUNTAS_FTA](
	[NUMERO] [bigint] NOT NULL,
	[NUMERO_CC_CAND_PREGUNTA_HDR] [bigint] NOT NULL,
	[NUMERO_CC_PREGUNTA_FTA] [bigint] NOT NULL,
	[RESPUESTA] [varchar](500) NULL,
	[RESPUESTA_CORRECTA] [varchar](500) NULL,
	[FECHA_EFECTIVA_DESDE] [datetime] NOT NULL,
	[FECHA_EFECTIVA_HASTA] [datetime] NOT NULL,
	[CREADO_POR] [bigint] NOT NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[ACTUALIZADO_POR] [bigint] NOT NULL,
	[FECHA_ACTUALIZACION] [datetime] NOT NULL,
 CONSTRAINT [CAND_CC_PREGUNTAS_FTA_PK1] PRIMARY KEY CLUSTERED 
(
	[NUMERO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CAND_CC_PREGUNTAS_FTA] ADD  DEFAULT (NEXT VALUE FOR [DBO].[CAND_CC_PREGUNTAS_FTA_S]) FOR [NUMERO]
GO

ALTER TABLE [dbo].[CAND_CC_PREGUNTAS_FTA]  WITH CHECK ADD  CONSTRAINT [CAND_CC_PREGUNTAS_FTA_FK1] FOREIGN KEY([NUMERO_CC_CAND_PREGUNTA_HDR])
REFERENCES [dbo].[CAND_CC_PREGUNTAS_HDR] ([NUMERO])
GO

ALTER TABLE [dbo].[CAND_CC_PREGUNTAS_FTA] CHECK CONSTRAINT [CAND_CC_PREGUNTAS_FTA_FK1]
GO

ALTER TABLE [dbo].[CAND_CC_PREGUNTAS_FTA]  WITH CHECK ADD  CONSTRAINT [CAND_CC_PREGUNTAS_FTA_FK2] FOREIGN KEY([NUMERO_CC_PREGUNTA_FTA])
REFERENCES [dbo].[CC_PREGUNTAS_FTA] ([NUMERO])
GO

ALTER TABLE [dbo].[CAND_CC_PREGUNTAS_FTA] CHECK CONSTRAINT [CAND_CC_PREGUNTAS_FTA_FK2]
GO


