USE [CMRISE]
GO

ALTER TABLE [dbo].[CAND_CC_PREGUNTAS_HDR] DROP CONSTRAINT [CAND_CC_PREGUNTAS_HDR_FK2]
GO

ALTER TABLE [dbo].[CAND_CC_PREGUNTAS_HDR] DROP CONSTRAINT [CAND_CC_PREGUNTAS_HDR_FK1]
GO

ALTER TABLE [dbo].[CAND_CC_PREGUNTAS_HDR] DROP CONSTRAINT [DF__CAND_CC_P__NUMER__318258D2]
GO

/****** Object:  Table [dbo].[CAND_CC_PREGUNTAS_HDR]    Script Date: 27/02/2020 17:53:09 ******/
DROP TABLE [dbo].[CAND_CC_PREGUNTAS_HDR]
GO

/****** Object:  Table [dbo].[CAND_CC_PREGUNTAS_HDR]    Script Date: 27/02/2020 17:53:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CAND_CC_PREGUNTAS_HDR](
	[NUMERO] [bigint] NOT NULL,
	[NUMERO_CAND_CC_EXAMEN] [bigint] NOT NULL,
	[NUMERO_CC_PREGUNTA_HDR] [bigint] NOT NULL,
	[FECHA_EFECTIVA_DESDE] [datetime] NOT NULL,
	[FECHA_EFECTIVA_HASTA] [datetime] NOT NULL,
	[CREADO_POR] [bigint] NOT NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[ACTUALIZADO_POR] [bigint] NOT NULL,
	[FECHA_ACTUALIZACION] [datetime] NOT NULL,
 CONSTRAINT [CAND_CC_PREGUNTAS_HDR_PK1] PRIMARY KEY CLUSTERED 
(
	[NUMERO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CAND_CC_PREGUNTAS_HDR] ADD  DEFAULT (NEXT VALUE FOR [CAND_CC_PREGUNTAS_HDR_S]) FOR [NUMERO]
GO

ALTER TABLE [dbo].[CAND_CC_PREGUNTAS_HDR]  WITH CHECK ADD  CONSTRAINT [CAND_CC_PREGUNTAS_HDR_FK1] FOREIGN KEY([NUMERO_CAND_CC_EXAMEN])
REFERENCES [dbo].[CAND_CC_EXAMENES] ([NUMERO])
GO

ALTER TABLE [dbo].[CAND_CC_PREGUNTAS_HDR] CHECK CONSTRAINT [CAND_CC_PREGUNTAS_HDR_FK1]
GO

ALTER TABLE [dbo].[CAND_CC_PREGUNTAS_HDR]  WITH CHECK ADD  CONSTRAINT [CAND_CC_PREGUNTAS_HDR_FK2] FOREIGN KEY([NUMERO_CC_PREGUNTA_HDR])
REFERENCES [dbo].[CC_PREGUNTAS_HDR] ([NUMERO])
GO

ALTER TABLE [dbo].[CAND_CC_PREGUNTAS_HDR] CHECK CONSTRAINT [CAND_CC_PREGUNTAS_HDR_FK2]
GO


