USE [CMRISE]
GO


CREATE TABLE [dbo].[CC_EXAMENES](
	[NUMERO] [bigint] NOT NULL DEFAULT (NEXT VALUE FOR CC_EXAMENES_S),
	[TITULO] [varchar](200) NOT NULL,
	[NOMBRE] [varchar](200),
	[DESCRIPCION] [varchar](300),
	[COMENTARIOS] [varchar](500),
	[TIEMPO_LIMITE] [smallint],
	[SALTAR_PREGUNTAS] BIT NOT NULL,
	[SALTAR_CASOS] BIT NOT NULL,
	[MOSTRAR_RESPUESTAS] BIT NOT NULL,
	[TIENE_PASSMARK] BIT NOT NULL,
	[ALEATORIO_GRUPO] BIT NOT NULL,
	[ALEATORIO_PREGUNTAS] BIT NOT NULL,
	[SELECCION_CASOS_ALEATORIOS] BIT NOT NULL,
	[MENSAJE_FINALIZACION] [varchar](500),
	[CONFIRMACION_ASISTENCIA] BIT NOT NULL,
	[DIPLOMA] BIT NOT NULL,
	[TIPO_PREGUNTA] [varchar](30) NOT NULL,
	[TIPO_EXAMEN] [varchar](30) NOT NULL,
	[VISIBILIDAD] [varchar](30) NOT NULL,
	[ESTATUS] [varchar](30) NOT NULL,
	[TEMA] [varchar](30) NOT NULL,
	[SOCIEDAD] [varchar](200) NOT NULL,
	[FECHA_EFECTIVA_DESDE] [date] NOT NULL,
	[FECHA_EFECTIVA_HASTA] [date] NOT NULL,
	[CREADO_POR] [bigint] NOT NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[ACTUALIZADO_POR] [bigint] NOT NULL,
	[FECHA_ACTUALIZACION] [datetime] NOT NULL,
	CONSTRAINT CC_EXAMENES_PK PRIMARY KEY(NUMERO)
)