USE [CMRISE]
GO


CREATE TABLE [dbo].[CC_EXAM_ASIGNACIONES](
	 [NUMERO] [bigint] NOT NULL DEFAULT (NEXT VALUE FOR CC_EXAM_ASSIGNACIONES_S)
	,[NUMERO_CC_EXAMEN]  [bigint] NOT NULL
	,[NUMERO_CORE_CASE]  [bigint] NOT NULL
	,[FECHA_EFECTIVA_DESDE] [date] NOT NULL
	,[FECHA_EFECTIVA_HASTA] [date] NOT NULL
	,[CREADO_POR] [bigint] NOT NULL
	,[FECHA_CREACION] [datetime] NOT NULL
	,[ACTUALIZADO_POR] [bigint] NOT NULL
	,[FECHA_ACTUALIZACION] [datetime] NOT NULL
	,CONSTRAINT CC_EXAM_ASIGNACIONES_PK1 PRIMARY KEY(NUMERO)
	,CONSTRAINT CC_EXAM_ASIGNACIONES_FK1 FOREIGN KEY(NUMERO_CC_EXAMEN) REFERENCES [dbo].[CC_EXAMENES](NUMERO)
	,CONSTRAINT CC_EXAM_ASIGNACIONES_FK2 FOREIGN KEY(NUMERO_CORE_CASE) REFERENCES [dbo].[CC_HDR](NUMERO)
	)
