USE [CMRISE]
GO

CREATE TABLE [dbo].[CC_HDR](
	[NUMERO] [bigint] NOT NULL DEFAULT (NEXT VALUE FOR [DBO].[CC_HDR_S]),
	[NOMBRE] [varchar](128) NOT NULL,
	[TEMA] [varchar](30) NULL,
	[HISTORIAL_CLINICO] [varchar](500) NULL,
	[DESCRIPCION_TECNICA] [varchar](500) NULL,
	[OPCION_INSEGURA] BIT NOT NULL,
	[ETIQUETAS] [varchar](500) NULL,
	[NOTA] [varchar](500) NULL,
	[ESTATUS] [varchar](30) NOT NULL,
	[SOCIEDAD] [varchar](200) NOT NULL,
	[FECHA_EFECTIVA_DESDE] [date] NOT NULL,
	[FECHA_EFECTIVA_HASTA] [date] NOT NULL,
	[CREADO_POR] [bigint] NOT NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[ACTUALIZADO_POR] [bigint] NOT NULL,
	[FECHA_ACTUALIZACION] [datetime] NOT NULL, 
	CONSTRAINT 	CC_HDR_PK1 PRIMARY KEY(NUMERO)
)