USE [CMRISE]
GO

CREATE TABLE DCM_EQUIPMENT (ID BIGINT NOT NULL DEFAULT(NEXT VALUE FOR DCM_EQUIPMENT_S)
                           ,CONVERSION_TYPE VARCHAR(50)
						   ,DEVICE_SERIAL_NUMBER VARCHAR(100)
						   ,INSTITUTION_ADDRESS VARCHAR(150)
						   ,INSTITUTION_NAME VARCHAR(100)
						   ,INSTITUTION_ALDEPARTMENT_NAME VARCHAR(50)
						   ,MANUFACTURER VARCHAR(100)
						   ,MANUFACTURER_MODEL_NAME VARCHAR(100)
						   ,MODALITY VARCHAR(50)
						   ,SOFTWARE_VERSION VARCHAR(100)
						   ,STATION_NAME VARCHAR(60)
						   ,SERIES_ID BIGINT
						   ,CREATED_DATE DATETIME
						   ,MODIFIED_DATE DATETIME
						   ,CONSTRAINT DCM_EQUIPMENT_PK1 PRIMARY KEY(ID)
						   ,CONSTRAINT DCM_EQUIPMENT_FK1 FOREIGN KEY(SERIES_ID) REFERENCES DCM_SERIES(ID)
						   )