USE [CMRISE]
GO

CREATE TABLE DCM_SERIES (ID BIGINT NOT NULL DEFAULT (NEXT VALUE FOR DCM_SERIES_S)
                        ,BODY_PART_EXAMINED VARCHAR(40)
						,LATERALITY VARCHAR(100)
						,OPERATORS_NAME VARCHAR(50)
						,PATIENT_POSITION VARCHAR(30)
						,PROTOCOL_NAME VARCHAR(100)
						,SERIES_DATETIME DATETIME
						,SERIES_DESCRIPTION VARCHAR(100)
						,SERIES_INSTANCE_UID VARCHAR(100)
						,SERIES_NUMBER INTEGER
						,STUDY_ID BIGINT
						,CREATED_DATE DATETIME
						,MODIFIED_DATE DATETIME
						,CONSTRAINT DCM_SERIES_PK1 PRIMARY KEY (ID)
						,CONSTRAINT DCM_SERIES_FK1 FOREIGN KEY (STUDY_ID) REFERENCES [dbo].[DCM_STUDY]([ID])
						)
