USE [CMRISE]
GO

CREATE TABLE DCM_INSTANCE
(
   ID                           BIGINT DEFAULT (NEXT VALUE FOR DCM_INSTANCE_S),
   ACQUISITION_DATETIME          DATETIME,
   CONTENT_DATETIME              DATETIME,
   EXPOSURE_TIME                 INTEGER,
   IMAGE_ORIENTATION             VARCHAR (40),
   IMAGE_POSITION                VARCHAR (80),
   IMAGE_TYPE                    VARCHAR (40),
   INSTANCE_NUMBER               INTEGER,
   KVP                          VARCHAR (40),
   MEDIA_STORAGE_SOP_INSTANCE_UID   VARCHAR (100),
   PATIENT_ORIENTATION           VARCHAR (40),
   PIXEL_SPACING                 FLOAT,
   SLICE_LOCATION                FLOAT,
   SLICE_THICKNESS               FLOAT,
   SOP_CLASS_UID                  VARCHAR (100),
   SOP_INSTANCE_UID               VARCHAR (100),
   TRANSFER_SYNTAX_UID            VARCHAR (100),
   WINDOW_CENTER                 VARCHAR (40),
   WINDOW_WIDTH                  VARCHAR (40),
   XRAY_TUBE_CURRENT              INTEGER,
   CREATED_DATE                  DATETIME,
   MODIFIED_DATE                 DATETIME,
   SERIES_ID                BIGINT,
   CONSTRAINT DCM_INSTANCE_PK1 PRIMARY KEY (ID),
   CONSTRAINT DCM_INSTANCE_FK1 FOREIGN KEY (SERIES_ID) REFERENCES DCM_SERIES(ID)
)