USE [CMRISE]
GO

/****** Object:  Table [dbo].[CC_EXAMENES]    Script Date: 27/03/2020 20:01:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MRQS_EXAMENES](
	[NUMERO] [bigint] NOT NULL DEFAULT (NEXT VALUE FOR [MRQS_EXAMENES_S]),
	[TITULO] [varchar](200) NOT NULL,
	[NOMBRE] [varchar](200) NULL,
	[DESCRIPCION] [varchar](300) NULL,
	[COMENTARIOS] [varchar](500) NULL,
	[TIEMPO_LIMITE] [smallint] NULL,
	[SALTAR_PREGUNTAS] [bit] NOT NULL,
	[SALTAR_CASOS] [bit] NOT NULL,
	[MOSTRAR_RESPUESTAS] [bit] NOT NULL,
	[TIENE_PASSMARK] [bit] NOT NULL,
	[ALEATORIO_GRUPO] [bit] NOT NULL,
	[ALEATORIO_PREGUNTAS] [bit] NOT NULL,
	[SELECCION_CASOS_ALEATORIOS] [bit] NOT NULL,
	[MENSAJE_FINALIZACION] [varchar](500) NULL,
	[CONFIRMACION_ASISTENCIA] [bit] NOT NULL,
	[DIPLOMA] [bit] NOT NULL,
	[TIPO_PREGUNTA] [varchar](30) NOT NULL,
	[TIPO_EXAMEN] [varchar](30) NOT NULL,
	[VISIBILIDAD] [varchar](30) NOT NULL,
	[ESTATUS] [varchar](30) NOT NULL,
	[TEMA] [varchar](30) NOT NULL,
	[SOCIEDAD] [varchar](200) NOT NULL,
	[FECHA_EFECTIVA_DESDE] [date] NOT NULL,
	[FECHA_EFECTIVA_HASTA] [date] NOT NULL,
	[CREADO_POR] [bigint] NOT NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[ACTUALIZADO_POR] [bigint] NOT NULL,
	[FECHA_ACTUALIZACION] [datetime] NOT NULL,
    CONSTRAINT [MRQS_EXAMENES_PK] PRIMARY KEY ([NUMERO])
	) 
GO


