USE [CMRISE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MRQS_IMAGENES_GRP](
	[NUMERO] [bigint] NOT NULL  DEFAULT (NEXT VALUE FOR [DBO].[MRQS_IMAGENES_GRP_S]),
	[NUMERO_FTA] [bigint] NOT NULL,
	[SECCION] [VARCHAR](100) NOT NUll,
	[TIPO] [VARCHAR](30) NOT NUll,
	[TITULO_SUPERIOR] [VARCHAR](500) ,
	[TITULO_INFERIOR] [VARCHAR](500) ,
	[TEXTO] [VARCHAR](500) ,
	[CREADO_POR] [bigint] NOT NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[ACTUALIZADO_POR] [bigint] NOT NULL,
	[FECHA_ACTUALIZACION] [datetime] NOT NULL,
    CONSTRAINT [MRQS_IMAGENES_GRP_PK1] PRIMARY KEY ([NUMERO]),
	CONSTRAINT [MRQS_IMAGENES_GRP_FK1] FOREIGN KEY([NUMERO_FTA]) REFERENCES [dbo].[MRQS_PREGUNTAS_FTA] ([NUMERO])
	)
GO