USE [CMRISE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MRQS_IMAGENES](
	[NUMERO] [bigint] NOT NULL  DEFAULT (NEXT VALUE FOR [DBO].[MRQS_IMAGENES_S]),
	[NUMERO_GRP] [bigint] NOT NULL,
	[NOMBRE_IMAGEN] VARCHAR(200) NOT NUll,
	[RUTA_IMAGEN] VARCHAR(500) NOT NULL,
	[CREADO_POR] [bigint] NOT NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[ACTUALIZADO_POR] [bigint] NOT NULL,
	[FECHA_ACTUALIZACION] [datetime] NOT NULL,
    CONSTRAINT [MRQS_IMAGENES_PK1] PRIMARY KEY ([NUMERO]),
	CONSTRAINT [MRQS_IMAGENES_FK1] FOREIGN KEY([NUMERO_GRP]) REFERENCES [dbo].[MRQS_IMAGENES_GRP] ([NUMERO])
	)
GO