USE [CMRISE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MRQS_LISTAS_PALABRAS](
	[NUMERO] [bigint] NOT NULL  DEFAULT (NEXT VALUE FOR [DBO].[MRQS_LISTAS_PALABRAS_S]),
	[NUMERO_FTA] [bigint] NOT NULL,
	[TIPO_REGISTRO] VARCHAR(30) NOT NULL,
	[PALABRA] [varchar](500) NULL,
	[SINONIMOS] [varchar] (2000) NULL,
	[CREADO_POR] [bigint] NOT NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[ACTUALIZADO_POR] [bigint] NOT NULL,
	[FECHA_ACTUALIZACION] [datetime] NOT NULL,
    CONSTRAINT [MRQS_LISTAS_PALABRAS_PK1] PRIMARY KEY ([NUMERO]),
	CONSTRAINT [MRQS_LISTAS_PALABRAS_FK1] FOREIGN KEY([NUMERO_FTA]) REFERENCES [dbo].[MRQS_PREGUNTAS_FTA] ([NUMERO])
	)
GO