USE [CMRISE]
GO

/****** Object:  Table [dbo].[TABLAS_UTILITARIAS_VALORES]    Script Date: 20/01/2020 14:06:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TABLAS_UTILITARIAS_VALORES](
	[NUMERO] [bigint] NOT NULL,
	[TIPO_TABLA] [varchar](30) NOT NULL,
	[CODIGO_TABLA] [varchar](30) NOT NULL,
	[SIGNIFICADO] [varchar](80) NOT NULL,
	[DESCRIPCION] [varchar](240) NULL,
	[ESTADO] [bit] NOT NULL,
	[FECHA_EFECTIVA_DESDE] [date] NOT NULL,
	[FECHA_EFECTIVA_HASTA] [date] NOT NULL,
	[CATEGORIA_ATTRIBUTO] [varchar](30) NULL,
	[ATRIBUTO1] [varchar](150) NULL,
	[ATRIBUTO2] [varchar](150) NULL,
	[ATRIBUTO3] [varchar](150) NULL,
	[ATRIBUTO4] [varchar](150) NULL,
	[ATRIBUTO5] [varchar](150) NULL,
	[CREADO_POR] [smallint] NOT NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[ACTUALIZADO_POR] [smallint] NOT NULL,
	[FECHA_ACTUALIZACION] [datetime] NOT NULL,
 CONSTRAINT [TABLAS_UTILITARIAS_VALORES_UN1] UNIQUE NONCLUSTERED 
(
	[TIPO_TABLA] ASC,
	[CODIGO_TABLA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


