USE [CMRISE]
GO

/****** Object:  View [dbo].[ADMON_USUARIOS_ROLES_V1]    Script Date: 05/04/2020 11:12:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER   VIEW [dbo].[ADMON_USUARIOS_ROLES_V1] AS
SELECT AUR.[NUMERO]
      ,AUR.[NUMERO_USUARIO]
	  ,AU.CURP
	  ,SUBSTRING(AR.NOMBRE, 1, 1)+''+CAST(AR.[NUMERO] AS VARCHAR)+''+CAST(AUR.[NUMERO_USUARIO] AS VARCHAR) MATRICULA
	  ,AU.NOMBRE NOMBRE_USUARIO
	  ,AU.APELLIDO_PATERNO+' '+AU.APELLIDO_MATERNO+' '+AU.NOMBRE NOMBRE_COMPLETO_USUARIO
	  ,AUR.[NUMERO_ROL]
	  ,AR.NOMBRE NOMBRE_ROL
	  ,AR.DESCRIPCION DESCRIPCION_ROL
	  ,AR.[FECHA_EFECTIVA_DESDE] FED_AR
      ,AR.[FECHA_EFECTIVA_HASTA] FEH_AR
	  ,AU.[FECHA_EFECTIVA_DESDE] FED_AU
      ,AU.[FECHA_EFECTIVA_HASTA] FEH_AU
      ,AUR.[FECHA_EFECTIVA_DESDE] FED_AUR
      ,AUR.[FECHA_EFECTIVA_HASTA] FEH_AUR
      ,AUR.[CREADO_POR]
      ,AUR.[FECHA_CREACION]
      ,AUR.[ACTUALIZADO_POR]
      ,AUR.[FECHA_ACTUALIZACION]
	  ,AU.APELLIDO_PATERNO
	  ,AU.APELLIDO_MATERNO
	  ,AU.CORREO_ELECTRONICO
	  ,AU.CONTRASENIA
  FROM [dbo].[ADMON_USUARIOS_ROLES] AUR
      ,[dbo].[ADMON_ROLES] AR
	  ,[dbo].[ADMON_USUARIOS] AU
 WHERE AUR.NUMERO_ROL = AR.NUMERO
   AND AUR.NUMERO_USUARIO = AU.NUMERO

GO


