USE [CMRISE]
GO

/****** Object:  View [dbo].[MRQS_PREGUNTAS_HDR_V2]    Script Date: 27/03/2020 16:13:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER    VIEW [dbo].[MRQS_PREGUNTAS_HDR_V2] AS
SELECT MPH.[NUMERO]
      ,MPH.[NOMBRE]
      ,MPH.[TITULO]
      ,MPH.[TIPO_PREGUNTA]
	  ,TUV1.SIGNIFICADO  TIPO_PREGUNTA_DESC
	  ,MPH.[TEMA_PREGUNTA]
	  ,TUV2.SIGNIFICADO  TEMA_PREGUNTA_DESC
      ,MPH.[ETIQUETAS]
      ,MPH.[COMENTARIOS]
      ,MPH.[ESTATUS]
	  ,TUV3.[SIGNIFICADO] ESTATUS_DESC
      ,MPH.[SOCIEDAD]
      ,MPH.[FECHA_EFECTIVA_DESDE]
      ,MPH.[FECHA_EFECTIVA_HASTA]
      ,MPH.[CREADO_POR]
      ,MPH.[FECHA_CREACION]
      ,MPH.[ACTUALIZADO_POR]
      ,MPH.[FECHA_ACTUALIZACION]
	  ,MPF.NUMERO NUMERO_MPF
	  ,MPF.TEXTO_PREGUNTA
	  ,MPF.TEXTO_SUGERENCIAS
	  ,MPF.RESPUESTA_CORRECTA
	  ,MPF.SINGLE_ANSWER_MODE
	  ,MPF.SUFFLE_ANSWER_ORDER
	  ,MPF.VALOR_PUNTUACION
	  ,MPF.METODO_PUNTUACION
  FROM [dbo].[MRQS_PREGUNTAS_HDR] MPH
      ,[dbo].[MRQS_PREGUNTAS_FTA] MPF
      ,[dbo].TABLAS_UTILITARIAS_VALORES TUV1
	  ,[dbo].TABLAS_UTILITARIAS_VALORES TUV2
	  ,[dbo].TABLAS_UTILITARIAS_VALORES TUV3
  WHERE 1=1
    AND MPH.NUMERO = MPF.NUMERO_HDR
    AND TUV1.TIPO_TABLA = 'TIPO_PREGUNTA'
    AND TUV1.CODIGO_TABLA = MPH.TIPO_PREGUNTA
	AND TUV2.TIPO_TABLA = 'TEMA_DE_PREGUNTA'
    AND TUV2.CODIGO_TABLA = MPH.TEMA_PREGUNTA
	AND TUV3.TIPO_TABLA = 'ESTATUS_MRQ'
    AND TUV3.CODIGO_TABLA = MPH.ESTATUS


GO


